/**
 * Generate docs/data-dictionary.md from information_schema + docs/erd/predicates.yaml
 * (tasks T077, spec FR-024). One section per relation: predicate, columns, keys and CHECKs.
 * Usage: pnpm db:dictionary [--test | --schema <name>]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import mysql from 'mysql2/promise';
import { dbConfig } from '../../src/lib/db/config';
import { schemaFromArgs } from './grants';

/** Minimal parser for the flat `table:\n  vi: …\n  en: …` format of predicates.yaml. */
export function parsePredicates(text: string): Record<string, { vi?: string; en?: string }> {
  const out: Record<string, { vi?: string; en?: string }> = {};
  let current: string | undefined;
  for (const raw of text.split('\n')) {
    if (!raw.trim() || raw.trimStart().startsWith('#')) continue;
    const top = /^([a-z_]+):\s*$/.exec(raw);
    if (top) {
      current = top[1];
      out[current] = {};
      continue;
    }
    const kv = /^\s+(vi|en):\s*(.*)$/.exec(raw);
    if (kv && current) out[current][kv[1] as 'vi' | 'en'] = kv[2].trim();
  }
  return out;
}

const md = (s: unknown) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
/** Inline code that may itself contain backticks; also drops MySQL's `_utf8mb4\'…\'` literal noise. */
const code = (s: unknown) => `\`\` ${md(s).replace(/_utf8mb4\\'/g, "'").replace(/\\'/g, "'")} \`\``;

async function main() {
  const schema = schemaFromArgs(process.argv.slice(2));
  const predicates = parsePredicates(readFileSync('docs/erd/predicates.yaml', 'utf8'));
  const conn = await mysql.createConnection(dbConfig('owner', { schema }));
  try {
    const q = async (sql: string) => ((await conn.query(sql, [schema]))[0] as any[]);
    const tables = await q(`SELECT TABLE_NAME t FROM information_schema.TABLES
      WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME <> '__drizzle_migrations' ORDER BY 1`);
    const columns = await q(`SELECT TABLE_NAME t, COLUMN_NAME c, COLUMN_TYPE ty, IS_NULLABLE n, COLUMN_DEFAULT d,
        GENERATION_EXPRESSION g, COLUMN_KEY k FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ?
        ORDER BY TABLE_NAME, ORDINAL_POSITION`);
    const keys = await q(`SELECT tc.TABLE_NAME t, tc.CONSTRAINT_NAME k, tc.CONSTRAINT_TYPE ty,
        GROUP_CONCAT(kcu.COLUMN_NAME ORDER BY kcu.ORDINAL_POSITION) cols,
        MAX(kcu.REFERENCED_TABLE_NAME) rt,
        GROUP_CONCAT(kcu.REFERENCED_COLUMN_NAME ORDER BY kcu.ORDINAL_POSITION) rcols
      FROM information_schema.TABLE_CONSTRAINTS tc
      JOIN information_schema.KEY_COLUMN_USAGE kcu ON kcu.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
       AND kcu.TABLE_NAME = tc.TABLE_NAME AND kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
      WHERE tc.TABLE_SCHEMA = ? GROUP BY tc.TABLE_NAME, tc.CONSTRAINT_NAME, tc.CONSTRAINT_TYPE
      ORDER BY tc.TABLE_NAME, FIELD(tc.CONSTRAINT_TYPE, 'PRIMARY KEY', 'UNIQUE', 'FOREIGN KEY'), tc.CONSTRAINT_NAME`);
    const checks = await q(`SELECT tc.TABLE_NAME t, cc.CONSTRAINT_NAME k, cc.CHECK_CLAUSE c
      FROM information_schema.CHECK_CONSTRAINTS cc
      JOIN information_schema.TABLE_CONSTRAINTS tc ON tc.CONSTRAINT_SCHEMA = cc.CONSTRAINT_SCHEMA
       AND tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME AND tc.CONSTRAINT_TYPE = 'CHECK'
      WHERE cc.CONSTRAINT_SCHEMA = ? ORDER BY tc.TABLE_NAME, cc.CONSTRAINT_NAME`);

    const out: string[] = [
      '# Data dictionary',
      '',
      '<!-- GENERATED by scripts/db/dictionary.ts from the migrated schema and docs/erd/predicates.yaml. Do not edit. -->',
      '',
      `${tables.length} relations. Types, keys and CHECK clauses are read from \`information_schema\`;`,
      'predicates (tân từ) come from `docs/erd/predicates.yaml`. Money is BIGINT VND; times are',
      'DATETIME(3) in UTC.',
      '',
    ];
    for (const { t } of tables) {
      const p = predicates[t] ?? {};
      out.push(`## ${t}`, '');
      out.push(`- **Tân từ**: ${p.vi ?? '_(missing)_'}`, `- **Predicate**: ${p.en ?? '_(missing)_'}`, '');
      out.push('| Column | Type | Null | Default / generated | Key |', '| --- | --- | --- | --- | --- |');
      for (const c of columns.filter((x) => x.t === t)) {
        const def = c.g ? `GENERATED: ${code(c.g)}` : c.d === null ? '' : code(c.d);
        out.push(`| \`${c.c}\` | ${md(c.ty)} | ${c.n === 'YES' ? 'yes' : 'no'} | ${def} | ${c.k || ''} |`);
      }
      out.push('', '**Keys**', '');
      for (const k of keys.filter((x) => x.t === t)) {
        const ref = k.ty === 'FOREIGN KEY' ? ` → \`${k.rt}\`(${k.rcols}) ON DELETE RESTRICT` : '';
        out.push(`- ${k.ty} \`${k.k}\` (${k.cols})${ref}`);
      }
      const cks = checks.filter((x) => x.t === t);
      if (cks.length) {
        out.push('', '**CHECK constraints**', '');
        for (const c of cks) out.push(`- \`${c.k}\`: ${code(c.c)}`);
      }
      out.push('');
    }
    const missing = tables.map((r) => r.t).filter((t) => !predicates[t]?.vi || !predicates[t]?.en);
    writeFileSync('docs/data-dictionary.md', out.join('\n'));
    console.log(`wrote docs/data-dictionary.md (${tables.length} relations)`);
    if (missing.length) {
      console.error(`missing predicates: ${missing.join(', ')}`);
      process.exit(1);
    }
  } finally {
    await conn.end();
  }
}

if (process.argv[1]?.endsWith('dictionary.ts')) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
