/**
 * Derive readable views from the single Chen source docs/erd/conceptual.puml:
 *   docs/erd/views/overview.puml  — entities and relationships only (no attributes)
 *   docs/erd/views/<area>.puml    — one subject area with its attributes
 * PlantUML lays a full Chen diagram out as one very wide row, so the report uses these views.
 * Usage: tsx scripts/erd/chen-views.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const AREAS: Record<string, string[]> = {
  catalog: ['MATERIAL_TYPE', 'PUBLISHER', 'AUTHOR', 'CATEGORY', 'BOOK', 'COPY', 'EXTERNAL_REFERENCE'],
  people: ['ACCOUNT', 'ROLE', 'PERMISSION', 'READER_TYPE', 'READER', 'LIBRARY_CARD', 'LOAN_POLICY_VERSION',
    'MATERIAL_TYPE'],
  circulation: ['READER', 'ACCOUNT', 'COPY', 'BOOK', 'LOAN_POLICY_VERSION', 'LOAN', 'LOAN_ITEM', 'RENEWAL',
    'RESERVATION'],
  money: ['READER', 'LOAN_ITEM', 'FINE', 'FINE_ADJUSTMENT', 'PAYMENT'],
};

interface Block { kind: 'entity' | 'relationship'; name: string; text: string; links: string[]; members: string[] }

export function parseChen(src: string): Block[] {
  const body = src.replace(/^@startchen.*\n/, '').replace(/@endchen\s*$/, '');
  const blocks: Block[] = [];
  // A block closes with `}` at the start of a line (nested multi-valued attributes close indented).
  const re = /^(entity|relationship) (\w+) \{\n([\s\S]*?)^\}\n((?:\w+ -\([^)]*\)- \w+\n)*)/gm;
  for (let m; (m = re.exec(body)); ) {
    const links = m[4].split('\n').filter(Boolean);
    blocks.push({
      kind: m[1] as Block['kind'],
      name: m[2],
      text: m[0],
      links,
      members: links.map((l) => l.split(' ').pop()!),
    });
  }
  return blocks;
}

function strip(b: Block): string {
  return `${b.kind} ${b.name} {\n}\n${b.links.map((l) => `${l}\n`).join('')}`;
}

function main() {
  const blocks = parseChen(readFileSync('docs/erd/conceptual.puml', 'utf8'));
  mkdirSync('docs/erd/views', { recursive: true });
  const header = (name: string, title: string) =>
    `@startchen ${name}\n' GENERATED by scripts/erd/chen-views.ts from docs/erd/conceptual.puml — do not edit.\ntitle ${title}\n`;
  writeFileSync('docs/erd/views/overview.puml',
    header('overview', 'Conceptual ERD — overview (attributes omitted)') + blocks.map(strip).join('') + '@endchen\n');
  for (const [area, entities] of Object.entries(AREAS)) {
    const set = new Set(entities);
    const parts = blocks.filter((b) =>
      b.kind === 'entity' ? set.has(b.name) : b.members.length > 0 && b.members.every((e) => set.has(e)));
    writeFileSync(`docs/erd/views/${area}.puml`,
      header(area, `Conceptual ERD — ${area}`) + parts.map((b) => b.text).join('') + '@endchen\n');
  }
  console.log(`wrote docs/erd/views/{overview,${Object.keys(AREAS).join(',')}}.puml`);
}

if (process.argv[1]?.endsWith('chen-views.ts')) main();
